INSERT INTO CATEGORY (ID_BOOK, TYPE_CATEGORY) VALUES (1, SCIENCE);
INSERT INTO CATEGORY (ID_BOOK, TYPE_CATEGORY) VALUES (2, SCIENCE);
INSERT INTO CATEGORY (ID_BOOK, TYPE_CATEGORY) VALUES (1, PSYCHOLOGY);