INSERT INTO CATEGORY (TYPE_CATEGORY, ID_BOOK) VALUES ('SCIENCE', 1);
INSERT INTO CATEGORY (TYPE_CATEGORY, ID_BOOK) VALUES ('SCIENCE', 2);
INSERT INTO CATEGORY (TYPE_CATEGORY, ID_BOOK) VALUES ('PSYCHOLOGY', 1);